image: gitpod/workspace-full

tasks:
  - init: "npm install"
    command: "npm run dev"
ports:
  - port: 3000
    onOpen: open-preview
    visibility: private

vscode:
  extensions:
    - svelte.svelte-vscode@104.8.0:82wQ4G6veIE3KBUYHpHgmw==
    - fivethree.vscode-svelte-snippets@0.5.0:rRkcaFrMb8wbTuH6kbGEQQ==
    - abusaidm.html-snippets@0.2.1:HrYIjYqOIABbxFB9g9kqXQ==